# fly.toml app configuration file generated for your-trading-bot on 2024-11-06T13:14:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-trading-bot'
primary_region = 'lax'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 8080
    handlers = ["http", "tls"]

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
